import type { Post } from "./types";

/** Dollar-quoted so bodies with quotes, newlines and Devanagari need no escaping. */
function q(value: string): string {
  const tag = "$vb$";
  if (value.includes(tag)) throw new Error("text contains the quote tag");
  return `${tag}${value}${tag}`;
}

const columns = ["slug", "title_en", "title_hi", "summary_en", "summary_hi", "body_en", "body_hi", "date", "place", "tags", "yt", "media", "live", "newsletter_sent_at"] as const;

/**
 * One insert per built-in story, for pasting into the Supabase SQL editor.
 * "on conflict do nothing": running it again never overwrites an editor's changes.
 */
export function seedSql(posts: Post[]): string {
  const rows = posts.map((p) => {
    const values = [
      q(p.slug),
      q(p.title_en),
      q(p.title_hi),
      q(p.summary_en),
      q(p.summary_hi),
      q(p.body_en),
      q(p.body_hi),
      q(p.date),
      q(p.place),
      `array[${p.tags.map(q).join(", ")}]::text[]`,
      q(p.yt),
      `${q(JSON.stringify(p.media))}::jsonb`,
      p.live ? "true" : "false",
      // A seeded story was public before the newsletter existed: it is never mailed when an editor first saves it.
      "now()",
    ];
    return `insert into public.posts (${columns.join(", ")})\nvalues (\n  ${values.join(",\n  ")}\n)\non conflict (slug) do nothing;`;
  });
  return [
    "-- The built-in stories as rows, so they become editable. Generated by `npm run seed:sql`; do not edit by hand.",
    "-- Safe to run again: existing slugs are left untouched.",
    "",
    ...rows,
    "",
  ].join("\n");
}
