-- The built-in stories as rows, so they become editable. Generated by `npm run seed:sql`; do not edit by hand.
-- Safe to run again: existing slugs are left untouched.

insert into public.posts (slug, title_en, title_hi, summary_en, summary_hi, body_en, body_hi, date, place, tags, yt, media, live, newsletter_sent_at)
values (
  $vb$silkyara-open-letter$vb$,
  $vb$The pain of the Himalayas is hidden in the tragedy of Silkyara$vb$,
  $vb$सिल्क्यारा की त्रासदी में छिपी है हिमालय की पीड़ा$vb$,
  $vb$An open letter to the Chief Minister of Uttarakhand after 41 workers walked out of the collapsed Silkyara tunnel.$vb$,
  $vb$$vb$,
  $vb$## Distinguished service in: Mr. Pushkar Singh Dhami, Chief Minister, Uttarakhand
On the auspicious occasion of World Mountain Day, heartfelt congratulations and best wishes to you and every hand and idea that made this work successful, for the lives of 41 workers trapped in the collapsed tunnel in Silkyara of Uttarkashi district, which the Uttarakhand government, under your able leadership, was able to save.
When the entire effort was being carried out in Silkyara to save the lives and ensure the safe return of 41 workers, I prayed to the Almighty and the Divine Mother that Silkyara's wish be fulfilled and that all 41 workers, having received the boon of life, return safely to their loved ones. There is immense joy in the success of Silkyara's wish.
## The Himalayas have a clear message for all of us: be careful in time
You used the state's best disaster management organisation, the SDRF, but their tireless efforts were not successful in the initial phase. You tried modern machines available locally, then ordered more from Delhi and other states. You invited the most skilled experts, even from abroad, and ultimately sought the NDRF and the Army. In the end, abandoning the machines, the work was done by the manual force of rat miners, and all 41 workers were rescued.
The persistent delay in results made me feel as if some invisible force was sending a mysterious message through the Himalayas: wake up early, stop messing around in the Himalayas, or your patience is beginning to wear thin.
## Ten years of warnings
In June 2013, the Kedarnath flood killed thousands of pilgrims. Between April and May 2016, 4,538 hectares of Uttarakhand forest burned; since statehood more than 44,000 hectares have been lost to fire. On 18 February 2021 the Nanda Devi glacier burst killed more than 200 at Vishnugad. On 4 October 2022, 27 mountaineers died on Draupadi ka Danda. In January 2023, over 500 homes cracked and sank in Joshimath. Then 41 workers spent 17 days inside Silkyara.
## The Blueprint of Uttarakhand, 1996
In 1996, under my leadership, a student-youth campaign team met the Government of India at North Block to propose the creation of Uttarakhand. Our report, the Blueprint of Uttarakhand, argued that the Himalaya is an oxygen bank and a water bank for the whole of humanity, and that environmental protection must come first in every development model. We asked for a Himalayan resource centre on the model of ICIMOD in Kathmandu, and a Green Bonus for the people who keep the mountains: ₹2,000 crore a year then, rising to ₹5,000 crore — at today's value, ₹29,000 to ₹36,000 crore a year.
> Physical grandeur exists in many places, but Badrinath Dham possesses spiritual divinity, which could be destroyed by unnecessary construction. — Jagadguru Swami Avimukteshwaranand, Shankaracharya, Jyotirmath
> Land use changes, deforestation, slope destabilisation due to dam and road construction, and debris dumping have multiplied the human and environmental impacts of these climate events. — Letter of 130 environmentalists on Joshimath, 6 April 2023
> Gaura Devi and our sisters from Chamoli were willing to have saws used on themselves to protect the trees. Today's system remains cruel to the Himalayas. — Bina Chaudhary, who fought to save Dhari Devi
## The request
Please ensure that all schemes and projects undergo periodic, quality-based, long-term evaluation, and approve every infrastructure project with the Himalayan environment and ecology at the centre. Take the necessary steps to prevent Himalayan cities and villages from becoming concrete jungles. If major policy changes are required, or some unnecessary projects must be withdrawn, please do so without hesitation. Overall, the government should listen to the genuine pain of the Himalayas.
Wishing a bright future for Uttarakhand under your able leadership,
Devotee Mukund Krishna Das ("Sainik Shiromani" Manoj Dhyani)$vb$,
  $vb$$vb$,
  $vb$2023-12-11$vb$,
  $vb$Dehradun, World Mountain Day$vb$,
  array[$vb$Open letter$vb$, $vb$Himalaya$vb$]::text[],
  $vb$$vb$,
  $vb$[]$vb$::jsonb,
  true,
  now()
)
on conflict (slug) do nothing;
insert into public.posts (slug, title_en, title_hi, summary_en, summary_hi, body_en, body_hi, date, place, tags, yt, media, live, newsletter_sent_at)
values (
  $vb$seed-bombers-2023$vb$,
  $vb$Seed Bombers of Uttarakhand$vb$,
  $vb$उत्तराखंड के सीड बॉम्बर्स$vb$,
  $vb$The 2023 Abhiyan opened with a seed-bombing campaign: volunteers set out to plant or sow two lakh seeds before Raksha Bandhan.$vb$,
  $vb$2023 का अभियान सीड बॉम्बिंग से शुरू हुआ: रक्षाबंधन से पहले दो लाख बीज बोने या रोपने का संकल्प।$vb$,
  $vb$Vrikshabandhan Abhiyan 2023 has set out with a seed-bombing campaign in Uttarakhand. Seed Bombers of Uttarakhand is the record of this beginning, a contribution to ecology and environment.
## First, Vrikshabandhan Abhiyan
Vrikshabandhan Abhiyan was conceptualised by Sainik Shiromani Manoj Dhyani in 2009 under the joint flagship of Uttarakhand Rajya Nirman Senani Sangh (Regd.) and RTI Lok Sewa (Regd.). It is one of the biggest word-of-mouth campaigns for a green planet. Before the monsoon, targets are set for the volunteers, preparation and strategies are worked out, and the plan is carried out during Sawan and Bhado, the months of the monsoon. It culminates on Raksha Bandhan, when a pledge to protect trees is taken through raksha sutras.
After year-on-year campaigns, the team of Vrikshabandhan Abhiyan volunteers has taken up the challenge to plant or sow **2,00,000 seeds** in 2023 as well.
To realise the dream and bring young people and villagers to the cause, Uttarakhand Rajya Nirman Senani Sangh (Regd.) began a series of talks. On 22 April 2023 it invited people to exchange ideas on the management of the Himalayas. On 25 May 2023, the birth anniversary of the freedom fighter Sridev Suman, the talk centred on the preservation of Uttarakhand's culture. As that culture deeply embraces the protection of ecology and environment, the talk deliberated on the core issue of the Uttarakhand movement: jal, jungle, jamin (water, forest, land). Then came the inception date of Vrikshabandhan Abhiyan, 5 June 2023, which is also [World Environment Day](https://www.un.org/en/observances/environment-day), when the volunteers learnt how to make seed bombs.
## What is a seed bomb
A seed bomb holds the seeds of flowers, trees or plants inside a ball of mud and organic fertiliser. It is prepared just before the monsoon arrives. As the rains come, the seed bombs are thrown around barren land, dry ponds and river banks, and inside forests. The idea is to start planting on a large scale, to hold back the loss of flora and fauna, and so to fight global warming.
The film of the 2023 seed-bombing campaign by Vrikshabandhan Abhiyan follows.
@youtube(https://youtu.be/XTmHXvDXcI0)$vb$,
  $vb$$vb$,
  $vb$2023-06-20$vb$,
  $vb$Uttarakhand$vb$,
  array[$vb$Seed bombing$vb$, $vb$Campaign$vb$]::text[],
  $vb$$vb$,
  $vb$[{"path":"images/seed-bombers-2023.jpg","url":"/images/seed-bombers-2023.jpg","type":"image","alt_en":"Volunteers of Vrikshabandhan Abhiyan 2023 seated on a grassy hillside with the campaign banner, Manoj Dhyani among them","alt_hi":"वृक्षाबंधन अभियान 2023 के स्वयंसेवक घास की ढलान पर अभियान के बैनर के साथ बैठे हुए, बीच में मनोज ध्यानी","width":1280,"height":720}]$vb$::jsonb,
  true,
  now()
)
on conflict (slug) do nothing;
insert into public.posts (slug, title_en, title_hi, summary_en, summary_hi, body_en, body_hi, date, place, tags, yt, media, live, newsletter_sent_at)
values (
  $vb$shriyantra-island$vb$,
  $vb$Why is the historic movement of Shriyantra Island forgotten?$vb$,
  $vb$श्रीयंत्र टापू का ऐतिहासिक आंदोलन क्यों भुला दिया गया?$vb$,
  $vb$10 November is Shriyantra Island Day in the Uttarakhand statehood movement. The 36-day fast, the police action of 1995, and the two agitators found in the Alaknanda.$vb$,
  $vb$$vb$,
  $vb$10 November is a day to remember the historic Shriyantra Island Day in the Uttarakhand state formation movement.
Two determined agitators, Shri Vishambar Singh Parmar and Shri Daulat Ram Pokhriyal, began a fast unto death on this island in the Alaknanda at Srinagar Garhwal, and continued it for 36 days.
On 10 November 1995, to break the fast, the PAC and the police carried out an action on the island. Two agitators, Yashodhar Benjwal and Rajesh Rawat, went missing. Their bodies were found seven or eight days later by ex-servicemen among the agitators, along the banks of the Alaknanda.
The Abhiyan returns to the Shriyantra Island garden every year so that the movement's price is not forgotten.$vb$,
  $vb$$vb$,
  $vb$2023-11-10$vb$,
  $vb$Shriyantra Island, Srinagar Garhwal$vb$,
  array[$vb$Statehood movement$vb$, $vb$Memory$vb$]::text[],
  $vb$$vb$,
  $vb$[]$vb$::jsonb,
  true,
  now()
)
on conflict (slug) do nothing;
insert into public.posts (slug, title_en, title_hi, summary_en, summary_hi, body_en, body_hi, date, place, tags, yt, media, live, newsletter_sent_at)
values (
  $vb$rampur-tiraha$vb$,
  $vb$We have to fight, brother — this is a long battle$vb$,
  $vb$लड़ना है भाई, यह लंबी लड़ाई है$vb$,
  $vb$On the folk song of the statehood movement, and the martyrs of Rampur Tiraha, 2 October 1994.$vb$,
  $vb$$vb$,
  $vb$2 October 1994 is a historical milestone in the Uttarakhand state formation movement. The martyrdom at Rampur Tiraha proved to be a turning point in the making of the state.
Among those who gave everything that night: the martyrs, the identified and unidentified agitators who went missing, the women who put their honour at stake, the fighters whose bodies were riddled with bullets, and countless others whose struggle is the foundation of Uttarakhand.
Hundreds of salutes to every honest force that fought for the state. Today is also the birth anniversary of Mahatma Gandhi and Lal Bahadur Shastri. Salutations to the great sons of the soil of India.
"Sainik Shiromani" Manoj Dhyani (Mukund Krishna Das)$vb$,
  $vb$$vb$,
  $vb$2017-05-15$vb$,
  $vb$Rampur Tiraha, Muzaffarnagar$vb$,
  array[$vb$Statehood movement$vb$, $vb$Folk song$vb$]::text[],
  $vb$$vb$,
  $vb$[]$vb$::jsonb,
  true,
  now()
)
on conflict (slug) do nothing;
